language: python
addons:
  firefox: "latest"
python:
  - "3.5"
install:
  - pip install django
  - pip install pyyaml
  - pip install selenium
  - pip install flake8
  - pip install coveralls
before_script:
  - flake8 ./leakntest/*
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.16.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - coverage run --source=leakntest manage.py test
after_success: coveralls
