language: python
python:
  - "3.5"
install:
  - pip install django
  - pip install flake8
  - pip install coveralls
before_script:
  - flake8 ./blog_tests/*
script:
  - coverage run --source='.' manage.py test
after_success: coveralls
