language: python
python:
  - "3.5"
install:
  - pip install django
  - pip install pyyaml
  - pip install selenium
  - pip install flake8
  - pip install coveralls
before_script:
  - flake8 ./leakntest/*
script:
  - coverage run --source=leakntest manage.py test
after_success: coveralls
