# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
