# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leakntest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='hash',
            new_name='hashword',
        ),
    ]
